#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Jun 12 07:23:05 2019

@author: michaelmoralesmoviles
"""

import pandas as pd
import numpy as np
import os
import sqlite3

path_guardado = 'Documents/GitHub/py-morales-proa-o-michael-oswaldo/04_dataFrames/data/csv/artwork_data.pickle'

df_completo_pickle = pd.read_pickle(path_guardado)
